### ISSUE TITLE
Is it okay to start training without imagenet pre-training?

### ISSUE THREAD

**Issue by zhillinhe** [xapaxca/swiftdepth#1]
Hello, I would like to start this project from scratch. Is it feasible to pre-train without ImageNet? What needs to be changed in the project? Also, what are the configs in the project? I've tried to select 'scratch' in the option.py, but it always needs to defauLt configs.

**Comment by zhillinhe** [comment]
I really look forward to hearing from you, thank you very much！

**Comment by xapaxca** [comment]
Hi LinManta,


Yes, you can train it without using pretrained weights from ImageNet.

[options.py](https://github.com/xapaxca/swiftdepth/blob/main/options.py) file was adapted from [Monodepth2](https://github.com/nianticlabs/monodepth2) with minor modifications, which means some options might not be applicable to SwiftDepth.

I recommend modifying the following line in [swiftformer_S_pretrained.py](https://github.com/xapaxca/swiftdepth/blob/main/configs/swiftformer_S_pretrained.py):

`depth_encoder, depth_decoder = build_depth(pretrained=True)`

to:

`depth_encoder, depth_decoder = build_depth(pretrained=False)`


I hope this helps.

**Comment by zhillinhe** [comment]
Hi xapaxca,

Thanks to your help, I train it successfully without using pretrained weights from ImageNet.

Your project is very rigorous, and I'm studying it seriously.

Besides, considering using the AdamW, I changed some parameters from options.py file to ensure convergence,  --learning_rate to 5e-4 and --num_epochs to 60. 

Thank you again for your help！
